return {
	cormando = {
		activatewhenbuilt = true,
		autoheal = 15,
		builddistance = 275,
		builder = true,
		buildpic = "CORMANDO.DDS",
		buildtime = 17100,
		canassist = true,
		canmove = true,
		canreclaim = true,
		canrepair = true,
		canrestore = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 50 22",
		collisionvolumetype = "box",
		energycost = 15500,
		energymake = 10,
		energystorage = 20,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1750,
		idleautoheal = 10,
		idletime = 900,
		mass = 750,
		maxacc = 0.4025,
		maxdec = 1.725,
		maxslope = 20,
		metalcost = 1200,
		movementclass = "ABOT3",
		nochasecategory = "VTOL",
		objectname = "Units/CORMANDO.s3o",
		radardistance = 1000,
		radardistancejam = 150,
		script = "Units/CORMANDO.cob",
		seismicsignature = 4,
		selfdestructas = "mediumExplosionGenericSelfd",
		selfdestructcountdown = 2,
		sightdistance = 600,
		speed = 75,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.65,
		turnrate = 1168.40002,
		upright = true,
		workertime = 150,
		buildoptions = {
			[1] = "corvalk",
			[2] = "corfink",
			[3] = "cormine1",
			[4] = "cormine2",
			[5] = "cormine3",
			[6] = "cormaw",
			[7] = "cordrag",
			[8] = "coreyes",
			[9] = "corjamt",
		},
		customparams = {
			fall_damage_multiplier = 0,
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			paratrooper = true,
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "buildert2",
			water_fall_damage_multiplier = 0,
			paralyzemultiplier = 0.2,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
				[2] = "custom:radarpulse_t1",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			commando_blaster = {
				accuracy = 0,
				areaofeffect = 8,
				beamtime = 0.2,
				beamttl = 1,
				tolerance = 10000,
				thickness = 3,
				corethickness = 0.2,
				laserflaresize = 4,
				impactonly = 1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 20,
				firestarter = 100,
				gravityaffected = "false",
				impulsefactor = 0,
				noselfdamage = true,
				predictboost = 0,
				proximitypriority = 1,
				range = 450,
				reloadtime = 0.5,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1000,
				damage = {
					default = 100,
					vtol = 50
				},
			},
			commando_grenades = {
				avoidfeature = false,
				burnblow = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				impulsefactor = 0.123,
				name = "Pop-up heavy g2g grenade launcher",
				noselfdamage = true,
				range = 750,
				reloadtime = 3,
				separation = 1.8,
				nogap = false,
				sizeDecay = 0.06,
				stages = 14,
				alphaDecay = 0.08,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "cannhvy1",
				targetmoveerror = 0.2,
				tolerance = 8000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 300,
				model = "legnade.s3o",


				weaponacceleration = -0.3,
				weapontimer = 0.01,
				weapontype = "Cannon",
				weaponvelocity = 700,
				startvelocity = 700,

				smoketrail = true,
				smokePeriod = 100,
				smoketime = 110,
				smokesize = 27,
				smokecolor = 0.70,
				smokeTrailCastShadow = true,

				cegtag = "missiletrail-grenadesmoke",
				areaofeffect = 124,
				avoidfeature = false,
				avoidfriendly = true,
				avoidground = true,
				burnblow = false,
				burst = 3,
				burstrate = 0.5,
				sprayangle = 500,
				accuracy = 1,
				bounce = 1,
				bounceslip = 0.60,
				bouncerebound = 0.40,
				numbounce = 5,
				groundbounce = true,
				collideenemy = true,
				collidefeature = false,
				collideground = true,
				collidefriendly = false,
				collidefirebase = false,
				collideneutral = false,
				flighttime = 2.05,
				proximityPriority = 1,
				gravityaffected = true,
				waterbounce = true,
				predictboost = 0.8,
				damage = {
					default = 375,
					subs = 300,
				},
				customparams = {
					noattackrangearc= 1,
					exclude_preaim = true
				}
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COMMANDO_BLASTER",
				onlytargetcategory = "NOTSUB"
			},
			[2] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "commando_grenades",
				onlytargetcategory = "SURFACE",
				maindir = "0 0 1",
				maxangledif = 300,
			},
		},
	},
}
