return {
	cormando = {
		activatewhenbuilt = true,
		autoheal = 15,
		builddistance = 275,
		builder = true,
		buildpic = "CORMANDO.DDS",
		buildtime = 17100,
		canassist = true,
		canmove = true,
		canreclaim = true,
		canrepair = true,
		canrestore = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 50 22",
		collisionvolumetype = "box",
		energycost = 15500,
		energymake = 10,
		energystorage = 20,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1750,
		idleautoheal = 10,
		idletime = 900,
		mass = 750,
		maxacc = 0.4025,
		maxdec = 1.725,
		maxslope = 20,
		metalcost = 1200,
		movementclass = "ABOT3",
		nochasecategory = "VTOL",
		objectname = "Units/CORMANDO.s3o",
		radardistance = 1000,
		radardistancejam = 150,
		script = "Units/CORMANDO.cob",
		seismicsignature = 4,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 600,
		speed = 75,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.65,
		turnrate = 1168.40002,
		upright = true,
		workertime = 150,
		buildoptions = {
			[1] = "corvalk",
			[2] = "corfink",
			[3] = "cormine1",
			[4] = "cormine2",
			[5] = "cormine3",
			[6] = "cormaw",
			[7] = "cordrag",
			[8] = "coreyes",
			[9] = "corjamt",
		},
		customparams = {
			fall_damage_multiplier = 0,
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			paratrooper = true,
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "buildert2",
			water_fall_damage_multiplier = 0,
			paralyzemultiplier = 0.5,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
				[2] = "custom:radarpulse_t1",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			commando_blaster = {
				accuracy = 0,
				areaofeffect = 8,
				beamtime = 0.2,
				beamttl = 1,
				tolerance = 10000,
				thickness = 3,
				corethickness = 0.2,
				laserflaresize = 4,
				impactonly = 1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 20,
				firestarter = 100,
				gravityaffected = "false",
				impulsefactor = 0,
				noselfdamage = true,
				predictboost = 0,
				proximitypriority = 1,
				range = 450,
				reloadtime = 0.5,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1000,
				damage = {
					default = 100
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COMMANDO_BLASTER",
				onlytargetcategory = "NOTSUB"
			},
		},
	},
}
